/**
 * This class is generated by jOOQ
 */
package ge.economy.law.model.tables.records;


import ge.economy.law.model.tables.CourtInstanceHistory;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Date;


/**
 * საქმის სასამართლო ინსტანციების ისტორია
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class CourtInstanceHistoryRecord extends UpdatableRecordImpl<CourtInstanceHistoryRecord> implements Record5<Integer, Integer, String, Date, Integer> {

    private static final long serialVersionUID = 1340026512;

    /**
     * Setter for <code>public.court_instance_history.id</code>.
     */
    public void setId(Integer value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>public.court_instance_history.id</code>.
     */
    public Integer getId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for <code>public.court_instance_history.case_id</code>.
     */
    public void setCaseId(Integer value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>public.court_instance_history.case_id</code>.
     */
    public Integer getCaseId() {
        return (Integer) getValue(1);
    }

    /**
     * Setter for <code>public.court_instance_history.note</code>.
     */
    public void setNote(String value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>public.court_instance_history.note</code>.
     */
    public String getNote() {
        return (String) getValue(2);
    }

    /**
     * Setter for <code>public.court_instance_history.insert_date</code>.
     */
    public void setInsertDate(Date value) {
        setValue(3, value);
    }

    /**
     * Getter for <code>public.court_instance_history.insert_date</code>.
     */
    public Date getInsertDate() {
        return (Date) getValue(3);
    }

    /**
     * Setter for <code>public.court_instance_history.court_instance_id</code>.
     */
    public void setCourtInstanceId(Integer value) {
        setValue(4, value);
    }

    /**
     * Getter for <code>public.court_instance_history.court_instance_id</code>.
     */
    public Integer getCourtInstanceId() {
        return (Integer) getValue(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Date, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Date, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CourtInstanceHistory.COURT_INSTANCE_HISTORY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CourtInstanceHistory.COURT_INSTANCE_HISTORY.CASE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CourtInstanceHistory.COURT_INSTANCE_HISTORY.NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return CourtInstanceHistory.COURT_INSTANCE_HISTORY.INSERT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return CourtInstanceHistory.COURT_INSTANCE_HISTORY.COURT_INSTANCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getInsertDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getCourtInstanceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourtInstanceHistoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourtInstanceHistoryRecord value2(Integer value) {
        setCaseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourtInstanceHistoryRecord value3(String value) {
        setNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourtInstanceHistoryRecord value4(Date value) {
        setInsertDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourtInstanceHistoryRecord value5(Integer value) {
        setCourtInstanceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourtInstanceHistoryRecord values(Integer value1, Integer value2, String value3, Date value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CourtInstanceHistoryRecord
     */
    public CourtInstanceHistoryRecord() {
        super(CourtInstanceHistory.COURT_INSTANCE_HISTORY);
    }

    /**
     * Create a detached, initialised CourtInstanceHistoryRecord
     */
    public CourtInstanceHistoryRecord(Integer id, Integer caseId, String note, Date insertDate, Integer courtInstanceId) {
        super(CourtInstanceHistory.COURT_INSTANCE_HISTORY);

        setValue(0, id);
        setValue(1, caseId);
        setValue(2, note);
        setValue(3, insertDate);
        setValue(4, courtInstanceId);
    }
}
