/**
 * This class is generated by jOOQ
 */
package ge.economy.law.model.tables.records;


import ge.economy.law.model.tables.CourtInstance;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Date;


/**
 * საქმის სასამართლო ინსტანციების ისტორია
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CourtInstanceRecord extends UpdatableRecordImpl<CourtInstanceRecord> implements Record4<Integer, Integer, String, Date> {

	private static final long serialVersionUID = 1522565018;

	/**
	 * Setter for <code>public.court_instance.court_instance_id</code>.
	 */
	public void setCourtInstanceId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.court_instance.court_instance_id</code>.
	 */
	public Integer getCourtInstanceId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.court_instance.case_id</code>.
	 */
	public void setCaseId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.court_instance.case_id</code>.
	 */
	public Integer getCaseId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.court_instance.note</code>.
	 */
	public void setNote(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.court_instance.note</code>.
	 */
	public String getNote() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.court_instance.insert_date</code>.
	 */
	public void setInsertDate(Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.court_instance.insert_date</code>.
	 */
	public Date getInsertDate() {
		return (Date) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, String, Date> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, String, Date> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return CourtInstance.COURT_INSTANCE.COURT_INSTANCE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return CourtInstance.COURT_INSTANCE.CASE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return CourtInstance.COURT_INSTANCE.NOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field4() {
		return CourtInstance.COURT_INSTANCE.INSERT_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getCourtInstanceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getCaseId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getNote();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value4() {
		return getInsertDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CourtInstanceRecord value1(Integer value) {
		setCourtInstanceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CourtInstanceRecord value2(Integer value) {
		setCaseId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CourtInstanceRecord value3(String value) {
		setNote(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CourtInstanceRecord value4(Date value) {
		setInsertDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CourtInstanceRecord values(Integer value1, Integer value2, String value3, Date value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CourtInstanceRecord
	 */
	public CourtInstanceRecord() {
		super(CourtInstance.COURT_INSTANCE);
	}

	/**
	 * Create a detached, initialised CourtInstanceRecord
	 */
	public CourtInstanceRecord(Integer courtInstanceId, Integer caseId, String note, Date insertDate) {
		super(CourtInstance.COURT_INSTANCE);

		setValue(0, courtInstanceId);
		setValue(1, caseId);
		setValue(2, note);
		setValue(3, insertDate);
	}
}
