/**
 * This class is generated by jOOQ
 */
package ge.economy.law.model.tables.records;


import ge.economy.law.model.tables.Judge;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * მოსამართლეები
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JudgeRecord extends UpdatableRecordImpl<JudgeRecord> implements Record2<Integer, String> {

	private static final long serialVersionUID = 344125106;

	/**
	 * Setter for <code>public.judge.judge_id</code>.
	 */
	public void setJudgeId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.judge.judge_id</code>.
	 */
	public Integer getJudgeId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.judge.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.judge.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Judge.JUDGE.JUDGE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Judge.JUDGE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getJudgeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JudgeRecord value1(Integer value) {
		setJudgeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JudgeRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JudgeRecord values(Integer value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached JudgeRecord
	 */
	public JudgeRecord() {
		super(Judge.JUDGE);
	}

	/**
	 * Create a detached, initialised JudgeRecord
	 */
	public JudgeRecord(Integer judgeId, String name) {
		super(Judge.JUDGE);

		setValue(0, judgeId);
		setValue(1, name);
	}
}
