/**
 * This class is generated by jOOQ
 */
package ge.economy.law.model.tables;


import ge.economy.law.model.Keys;
import ge.economy.law.model.Public;
import ge.economy.law.model.tables.records.CourtInstanceHistoryRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * საქმის სასამართლო ინსტანციების ისტორია
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CourtInstanceHistory extends TableImpl<CourtInstanceHistoryRecord> {

	private static final long serialVersionUID = 2119408900;

	/**
	 * The reference instance of <code>public.court_instance_history</code>
	 */
	public static final CourtInstanceHistory COURT_INSTANCE_HISTORY = new CourtInstanceHistory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CourtInstanceHistoryRecord> getRecordType() {
		return CourtInstanceHistoryRecord.class;
	}

	/**
	 * The column <code>public.court_instance_history.id</code>.
	 */
	public final TableField<CourtInstanceHistoryRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.court_instance_history.case_id</code>.
	 */
	public final TableField<CourtInstanceHistoryRecord, Integer> CASE_ID = createField("case_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.court_instance_history.note</code>.
	 */
	public final TableField<CourtInstanceHistoryRecord, String> NOTE = createField("note", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * The column <code>public.court_instance_history.insert_date</code>.
	 */
	public final TableField<CourtInstanceHistoryRecord, Date> INSERT_DATE = createField("insert_date", org.jooq.impl.SQLDataType.DATE.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.court_instance_history.court_instance_id</code>.
	 */
	public final TableField<CourtInstanceHistoryRecord, Integer> COURT_INSTANCE_ID = createField("court_instance_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.court_instance_history</code> table reference
	 */
	public CourtInstanceHistory() {
		this("court_instance_history", null);
	}

	/**
	 * Create an aliased <code>public.court_instance_history</code> table reference
	 */
	public CourtInstanceHistory(String alias) {
		this(alias, COURT_INSTANCE_HISTORY);
	}

	private CourtInstanceHistory(String alias, Table<CourtInstanceHistoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private CourtInstanceHistory(String alias, Table<CourtInstanceHistoryRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "საქმის სასამართლო ინსტანციების ისტორია");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<CourtInstanceHistoryRecord, Integer> getIdentity() {
		return Keys.IDENTITY_COURT_INSTANCE_HISTORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CourtInstanceHistoryRecord> getPrimaryKey() {
		return Keys.COURT_INSTANCE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CourtInstanceHistoryRecord>> getKeys() {
		return Arrays.<UniqueKey<CourtInstanceHistoryRecord>>asList(Keys.COURT_INSTANCE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CourtInstanceHistory as(String alias) {
		return new CourtInstanceHistory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public CourtInstanceHistory rename(String name) {
		return new CourtInstanceHistory(name, null);
	}
}
